Repository rapidsai/integration, pull requests merged in 2020-08, with the labels that each got.

#95 FIX Add 0.16 RAPIDS to nightly axis & remove `libcumlprims` from `rapids-build-env`
  ci/axis/nightly.yaml
  conda/recipes/rapids-build-env/meta.yaml
Labels: 3 - Ready for Review

#96 FIX Correct conda recipes to use RAPIDS version
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-doc-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
Labels: 3 - Ready for Review, bug

#97 FIX Update RAPIDS versions in axis files
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-doc-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
Labels: 3 - Ready for Review, bug

#98 FIX Include VERSION_SUFFIX in pkg version
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-doc-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
Labels: 3 - Ready for Review, bug

#102 FIX Use our nightly cupy for CUDA 11 and restrict numba <0.51
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review

#105 FIX Update test PATHs and remove duplicate installs
  ci/test/cudf.sh
  ci/test/cugraph.sh
  ci/test/cuml.sh
  ci/test/cuspatial.sh
  ci/test/daskcuda.sh
  ci/test/integration.sh
Labels: 4 - Needs Reviewer, 4 - Needs Tests

#106 FIX Add /opt/conda/bin to Path Variable
  ci/test/cudf.sh
  ci/test/cugraph.sh
  ci/test/cuml.sh
  ci/test/cuspatial.sh
  ci/test/daskcuda.sh
  ci/test/integration.sh
  ci/test/rmm.sh
Labels: 3 - Ready for Review, bug

#101 [REVIEW] Add MNMG Linear Regression simple fit
  ci/test/integration.sh
  test/cuml/test_mnmg.py
Labels: 4 - Needs Tests, 5 - DO NOT MERGE, tests

#104 [BUG] Sorted results to account for renumbering changing the order
  test/cugraph/test_pagerank.py
Labels: tests

#107 Set xgboost to 1.2.0 for all CUDA versions
  ci/cpu/build.sh
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review, xgboost

#111 Tie xgboost version to rapids version
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/versions.yaml
Labels: 4 - Needs Tests, xgboost

#108 Bump Dask + Distributed to 2.23.0
  conda/recipes/versions.yaml
Labels: 4 - Needs Tests, 4 - Waiting on Author, 5 - DO NOT MERGE

#109 ENH Update numba versioning to pull 0.51
  conda/recipes/versions.yaml
Labels: 5 - Ready to Merge

#118 [RELEASE] RAPIDS v0.15
  .github/CODEOWNERS
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
  ci/cpu/build.sh
  ci/cpu/conda-pack.sh
  ci/test/cudf.sh
  ci/test/cugraph.sh
  ci/test/cuml.sh
  ci/test/cuspatial.sh
  ci/test/daskcuda.sh
  ci/test/integration.sh
  ci/test/notebooks.sh
  ci/test/rmm.sh
  conda/recipes/README.md
  conda/recipes/nightly-versions.yaml
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-doc-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
  test/cudf/test_diningparty.py
  test/cugraph/test_pagerank.py
  test/cuml/test_mnmg.py
Labels: ! - Release, 3 - Ready for Review
