Repository rapidsai/integration, pull requests merged in 2020-10, with the labels that each got.

#141 Require `nvtx`
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
Labels: 5 - Ready to Merge

#142 Add v0.17 to axis
  ci/axis/nightly.yaml
Labels: 3 - Ready for Review

#143 Remove dask-xgboost
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review

#145 [REVIEW] pin faiss to =1.6.3
  conda/recipes/versions.yaml
Labels: 5 - Merge After Dependencies

#147 FIX Add `setuptools` to `rapids` meta pkg
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review, bug

#148 FIX Update NCCL versions.yaml
  conda/recipes/versions.yaml
Labels: 4 - Needs Tests

#154 ENH Remove conda from `build-env` and update conda-build version
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review, conda

#155 Revert #154 removal of conda, keeps conda/conda-build version updates
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/versions.yaml
Labels: bug

#159 v0.16 Release
  README.md
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
  ci/test/cudf.sh
  ci/test/cugraph.sh
  ci/test/notebooks.sh
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-doc-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
  conda/recipes/versions.yaml
  test/cugraph/test_pagerank.py
Labels: ! - Release

#162 Update axes to v0.17
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
Labels: 3 - Ready for Review

#164 Ignore missing files during conda pack
  ci/cpu/conda-pack.sh
Labels: 3 - Ready for Review

#166 Bump xgboost to v0.17
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review
