Repository rapidsai/integration, pull requests merged in 2020-12, with the labels that each got.

#182 Update xgboost version to latest
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review

#183 XGBoost version is based on rapids minor version
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/versions.yaml
Labels: 3 - Ready for Review

#187 ENH Allow blazing meta pkgs to fail
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
  ci/cpu/build.sh
Labels: 4 - Needs Reviewer

#181 close open-ended pins for cuxfilter dependencies
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/versions.yaml
Labels: 4 - Needs Tests

#189 ENH Remove 0.17 from branch-0.18
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
  ci/cpu/build.sh
Labels: 4 - Needs Tests

#193 ENH Remove CUDA default conda builds
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/cpu/build.sh
Labels: 4 - Needs Reviewer, 4 - Needs Tests, tech debt

#190 FIX Add rapids-pytest-benchmark pkg for cugraph tests
  conda/recipes/rapids-build-env/meta.yaml
Labels: 4 - Needs Tests

#195 Add typing extensions
  conda/recipes/rapids-build-env/meta.yaml
Labels: 4 - Needs Tests

#188 Enable parallelism in cudf & dask-cudf pytests
  ci/test/cudf.sh
  conda/recipes/rapids-build-env/meta.yaml
Labels: 5 - Ready to Merge

#199 ENH Open gcc pinning to allow for new conda-forge gcc 9.3 pkgs
  conda/recipes/versions.yaml
Labels: 4 - Needs Reviewer, conda
