Repository rapidsai/integration, pull requests merged in 2021-05, with the labels that each got.

#269 Switch integration to calver
  ci/axis/nightly.yaml
  ci/axis/release.yaml
  ci/axis/tests.yaml
  conda/recipes/rapids-blazing/meta.yaml
Labels: 3 - Ready for Review, 5 - DO NOT MERGE

#198 upgrade spdlog to 1.8.5 and above
  conda/recipes/versions.yaml
Labels: 4 - Needs Tests

#280 Update environment variable used to determine `cuda_version`
  conda/recipes/blazingsql-build-env/meta.yaml
  conda/recipes/blazingsql-notebook-env/meta.yaml
  conda/recipes/rapids-blazing/meta.yaml
  conda/recipes/rapids-build-env/meta.yaml
  conda/recipes/rapids-notebook-env/meta.yaml
  conda/recipes/rapids-xgboost/meta.yaml
  conda/recipes/rapids/meta.yaml
Labels: improvement, non-breaking
